name: publish python package to PyPI

on:  # 这里我设置了两个事件，一般的push tag以v开头，用来测试发布，而release用来正式发布
  release:
    types: [published]
  push:
    # Alternative: only build for tags.
    tags:
      - 'v*'
jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build_wheels:  # 这里分别用了别人现成的脚本来在多平台上编译，实际上这个任务要在每个os上面都跑一遍
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}

      - name: publish to PYPI
        if: github.event_name == 'release' && github.event.action == 'published'  # 有了这句话才能只在发布的时候执行
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
